### ISSUE TITLE
No such file or directory <linux/can.h> on alpine linux- HomeAsssistant

### ISSUE THREAD

**Issue by rudolf992** [c3re/can2mqtt#23]
Hello, 

I am trying to install and run the script on alpine linux, which is the base for HomeAssistant. After installing GO and gcc, I got this issue and have no ideea how to solve. Can-utils is running on system.

![image](https://user-images.githubusercontent.com/32765188/205453865-ab35c212-0983-4bd7-a700-bbc43d103719.png)

**Comment by mxmxchere** [comment]
Hi @rudolf992, thanks for reaching out :) Are you building inside a container that has a public image? If this is the case i can try to reproduce the error on my side and have a look

**Comment by mxmxchere** [comment]
Ok, i tried out ghcr.io/home-assistant/home-assistant:stable and was able to reproduce you error...

**Comment by rudolf992** [comment]
Good to hear that, everything was standard constainer of HASS, just installed can-utils before.
Hopefully you find,  a solution, on my knowledge level can not sort out.

**Comment by mxmxchere** [comment]
Hi, i replaced the old canbus-lib (which relied on cgo) with a new one (https://github.com/brutella/can) . I also added binary builds (with cgo disabled) of can2mqtt to the release page (https://github.com/c3re/can2mqtt/releases/tag/v1.1.0) and i was able to execute it in the alpine container directly. I hope that solved your issue :)

**Comment by rudolf992** [comment]
V.1.1.0 package solved the issue, code is running.
 What I noticed ~/go/bin is empty after install, however can2mqtt can be run.

**Comment by mxmxchere** [comment]
fantastic, thanks for the feedback. Regarding the go/bin dir: i'll update the installation instructions to just the binaries from now on.
